export * from './itemController.service';
import { ItemControllerService } from './itemController.service';
export * from './mediaController.service';
import { MediaControllerService } from './mediaController.service';
export * from './productExtController.service';
import { ProductExtControllerService } from './productExtController.service';
export * from './restTest.service';
import { RestTestService } from './restTest.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './venueController.service';
import { VenueControllerService } from './venueController.service';
export const APIS = [ItemControllerService, MediaControllerService, ProductExtControllerService, RestTestService, UserControllerService, VenueControllerService];
