/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { BaseResponse } from '../model/baseResponse';
import { ItemDTO } from '../model/itemDTO';
import { ProductDTO } from '../model/productDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ItemControllerService {

    protected basePath = 'https://restapi.oenginoz.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createCategory
     * 
     * @param itemDTO itemDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createCategoryUsingPOST(itemDTO: ItemDTO, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public createCategoryUsingPOST(itemDTO: ItemDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public createCategoryUsingPOST(itemDTO: ItemDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public createCategoryUsingPOST(itemDTO: ItemDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemDTO === null || itemDTO === undefined) {
            throw new Error('Required parameter itemDTO was null or undefined when calling createCategoryUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/createCategory`,
            itemDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * createMenu
     * 
     * @param itemDTO itemDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createMenuUsingPOST(itemDTO: ItemDTO, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public createMenuUsingPOST(itemDTO: ItemDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public createMenuUsingPOST(itemDTO: ItemDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public createMenuUsingPOST(itemDTO: ItemDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemDTO === null || itemDTO === undefined) {
            throw new Error('Required parameter itemDTO was null or undefined when calling createMenuUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/createMenu`,
            itemDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * createProduct
     * 
     * @param productDTO productDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createProductUsingPOST(productDTO: ProductDTO, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public createProductUsingPOST(productDTO: ProductDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public createProductUsingPOST(productDTO: ProductDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public createProductUsingPOST(productDTO: ProductDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (productDTO === null || productDTO === undefined) {
            throw new Error('Required parameter productDTO was null or undefined when calling createProductUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/createProduct`,
            productDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteItem
     * 
     * @param itemDTO itemDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteItemUsingPOST(itemDTO: ItemDTO, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public deleteItemUsingPOST(itemDTO: ItemDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public deleteItemUsingPOST(itemDTO: ItemDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public deleteItemUsingPOST(itemDTO: ItemDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemDTO === null || itemDTO === undefined) {
            throw new Error('Required parameter itemDTO was null or undefined when calling deleteItemUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/deleteItem`,
            itemDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllItemsByGuid
     * 
     * @param guid guid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllItemsByGuidUsingPOST(guid: string, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public getAllItemsByGuidUsingPOST(guid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public getAllItemsByGuidUsingPOST(guid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public getAllItemsByGuidUsingPOST(guid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (guid === null || guid === undefined) {
            throw new Error('Required parameter guid was null or undefined when calling getAllItemsByGuidUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/getItemsByGuid`,
            guid,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllItems
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllItemsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public getAllItemsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public getAllItemsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public getAllItemsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<BaseResponse>(`${this.basePath}/getItems`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getUserItems
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUserItemsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public getUserItemsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public getUserItemsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public getUserItemsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<BaseResponse>(`${this.basePath}/getUserItems`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateItem
     * 
     * @param productDTO productDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateItemUsingPOST(productDTO: ProductDTO, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public updateItemUsingPOST(productDTO: ProductDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public updateItemUsingPOST(productDTO: ProductDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public updateItemUsingPOST(productDTO: ProductDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (productDTO === null || productDTO === undefined) {
            throw new Error('Required parameter productDTO was null or undefined when calling updateItemUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/updateItem`,
            productDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
