/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { BaseResponse } from '../model/baseResponse';
import { VenueDTO } from '../model/venueDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VenueControllerService {

    protected basePath = 'https://restapi.oenginoz.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getVenueDetail
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getVenueDetailUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public getVenueDetailUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public getVenueDetailUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public getVenueDetailUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getVenueDetailUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<BaseResponse>(`${this.basePath}/venueDetail/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * newVenue
     * 
     * @param venueDTO venueDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public newVenueUsingPOST(venueDTO: VenueDTO, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public newVenueUsingPOST(venueDTO: VenueDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public newVenueUsingPOST(venueDTO: VenueDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public newVenueUsingPOST(venueDTO: VenueDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (venueDTO === null || venueDTO === undefined) {
            throw new Error('Required parameter venueDTO was null or undefined when calling newVenueUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/newVenue`,
            venueDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateVenue
     * 
     * @param venueDTO venueDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateVenueUsingPOST(venueDTO: VenueDTO, observe?: 'body', reportProgress?: boolean): Observable<BaseResponse>;
    public updateVenueUsingPOST(venueDTO: VenueDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponse>>;
    public updateVenueUsingPOST(venueDTO: VenueDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponse>>;
    public updateVenueUsingPOST(venueDTO: VenueDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (venueDTO === null || venueDTO === undefined) {
            throw new Error('Required parameter venueDTO was null or undefined when calling updateVenueUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BaseResponse>(`${this.basePath}/updateVenue`,
            venueDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
