/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ItemDTO {
    description?: string;
    id?: number;
    image?: string;
    itemGuid?: string;
    itemType?: string;
    name?: string;
    orderNo?: number;
    parentId?: number;
    status?: string;
    videoUrl?: string;
}
