/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MediaDTO } from './mediaDTO';


export interface ProductDTO {
    calories?: number;
    description?: string;
    id?: number;
    image?: string;
    itemGuid?: string;
    itemType?: string;
    medias?: Array<MediaDTO>;
    name?: string;
    orderNo?: number;
    parentId?: number;
    prepareTime?: number;
    price?: number;
    productStatus?: string;
    status?: string;
    videoUrl?: string;
    virtualCategory?: boolean;
    virtualOrderNo?: number;
}
