/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface VenueDTO {
    foursquareId?: string;
    foursquareToken?: string;
    infoScreenStatus?: number;
    venueId?: number;
    venueImage?: string;
    venueName?: string;
}
